[viewer]
git-tree-sha1 = "b4578c02a6cff9dd0cb0355114bff77eca0755fb"
lazy = true

    [[viewer.download]]
    sha256 = "86a69cc62094e9de22fb7a713c709a5eaaad6b3b3f7ec76c24fd56c3599c59af"
    url = "https://github.com/JuliaSatcomFramework/CesiumLink.jl/releases/download/viewer-4be9af1/viewer.tar.gz"
